
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/buildoptima?currentSchema=buildoptima

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true

  flyway:
    url: jdbc:postgresql://localhost:5432/buildoptima
    user: postgres
    password: root
    schemas: buildoptima
    locations: classpath:db/migration
    baseline-on-migrate: true


springdoc:
  api-docs:
    path: /api-docs


