spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/buildoptima?currentSchema=buildoptima

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    locations:
      - classpath:db/migration

  mail:
    host: smtp.gmail.com
    port: 587
    username: managementstaffing09@gmail.com
    password: slth mddf xtog hlet
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /api-docs


server:
  port: 80
  servlet:
    context-path: /api/v1

cloud:
  aws:
    region:
      auto: false
      static: us-east-1
      use-default-aws-region-chain: true
    stack:
      auto: false
    credentials:
      access-key: AKIA2AHFPMZSNI2KGCUN
      secret-key: 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


platform:
  security:
    jwt:
      issuer: buildoptima
      privateKeyPath: data/keys/private.der
      publicKeyPath: data/keys/public.der
      signatureAlgorithm: RS256
      authorizationHeader: "Authorization"
      authorizationHeaderPrefix: "Bearer "
      accessToken:
        validity: 15 #minutes
      refreshToken:
        validity: 60 #hours

aws:
  properties:
    s3:
      imageBucketName: buildoptima
      dataBucketName: buildoptima-data

logging:
  level:
    com:
      amazonaws:
        internal:
          com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error


host:
  address: http://localhost:3000

opensearch:
  properties:
    username: buildoptima
    password: Buildoptima2022.
    hostname: search-buildoptima-qlgtbnqklfvdvcdj576ghisvmu.us-east-1.es.amazonaws.com
    port: 443
    schema: https
    indexName: buildoptima
    requestBodiesPath: src/main/resources/opensearch/
    indexMappingFileName: mappings.json
    indexSettingsFileName: settings.json

page:
  skip: 0
  take: 10