spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/buildoptima?currentSchema=buildoptima

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations:
      - classpath:db/migration

  mail:
    host: smtp.gmail.com
    port: 587
    username: managementstaffing09@gmail.com
    password: slth mddf xtog hlet
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /api-docs


server:
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-alias: tomcat
    enabled: true
  servlet:
    context-path: /api/v1

cloud:
  aws:
    region:
      auto: false
      static: us-east-1
      use-default-aws-region-chain: true
    stack:
      auto: false

platform:
  security:
    jwt:
      issuer: buildoptima
      privateKeyPath: data/keys/private.der
      publicKeyPath: data/keys/public.der
      signatureAlgorithm: RS256
      authorizationHeader: "Authorization"
      authorizationHeaderPrefix: "Bearer "
      accessToken:
        validity: 15 #minutes
      refreshToken:
        validity: 60 #hours

aws:
  properties:
    s3:
      bucketName: buildoptima

logging:
  level:
    com:
      amazonaws:
        internal:
          com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

host:
  ip: localhost

page:
  skip: 0
  take: 10
