spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/build_optima?currentSchema=build_optima

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    url: jdbc:postgresql://localhost:5432/build_optima
    user: postgres
    password: root
    schemas: build_optima
    locations: classpath:db/migration
    baseline-on-migrate: true
