spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/buildoptima?currentSchema=buildoptima

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    url: jdbc:postgresql://localhost:5432/buildoptima
    user: postgres
    password: root
    schemas: buildoptima
    locations: classpath:db/migration


springdoc:
  api-docs:
    path: /api-docs



platform:
  security:
    jwt:
      publicKeyPath: data/keys/public.der
      privateKeyPath: data/keys/private.der
      signatureAlgorithm: RS256
      authorizationHeader: "Authorization"
      authorizationHeaderPrefix: "Bearer "
      issuer: "Buildoptima API"
      refreshToken:
        validity: 60 #minutes
      accessToken:
        validity: 6 #months

#debug: true