
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/buildoptima?currentSchema=buildoptima

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        dialect:

  flyway:
    url: jdbc:postgresql://localhost:5432/buildoptima
    user: postgres
    password: root
    schemas: buildoptima
    locations: classpath:db/migration
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: managementstaffing09@gmail.com
    password: slth mddf xtog hlet
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /api-docs


