spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/buildoptima?currentSchema=buildoptima

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
