
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/buildoptima?currentSchema=buildoptima


  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    url: jdbc:postgresql://localhost:5432/buildoptima
    user: postgres
    password: root
    schemas: buildoptima
    locations: classpath:db/migration
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: managementstaffing09@gmail.com
    password: slth mddf xtog hlet
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /api-docs


server:
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-alias: tomcat
    enabled: true

platform:
  security:
    jwt:
      issuer: buildoptima
      privateKeyPath: data/keys/private.der
      publicKeyPath: data/keys/public.der
      signatureAlgorithm: RS256
      authorizationHeader: "Authorization"
      authorizationHeaderPrefix: "Bearer "
      accessToken:
        validity: 1 #days
      refreshToken:
        validity: 6 #months

host:
  ip: 3.95.166.178
