version: '3.8'

services:
  localstack:
    image: localstack/localstack:0.10.6
    container_name: localstack
    ports:
      - "4566:4566"
      - "8082:8082"
      - "4567:4567"
    environment:
      - SERVICES=s3:4566,sqs:4567
      - HOSTNAME_EXTERNAL=localhost
      - DEBUG=1
      - PORT_WEB_UI=8082
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack

  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:1.3.0
    environment:
      - discovery.type=single-node
      - "DISABLE_SECURITY_PLUGIN=true"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
