name: CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          name: buildoptima
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build The Application
        run: mvn clean package -DskipTests
