name: CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          name: buildoptima
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run LocalStack Container
        run: docker-compose -f docker/docker-compose-test.yml up -d
      - name: Run Tests
        run: |
          mvn clean test --batch-mode
        
        
      

    
